
FROM python:3.9 as builder

WORKDIR /app

COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt


COPY . .


FROM python:3.9-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local


ENV PATH=/root/.local/bin:$PATH
ENV PYTHONUNBUFFERED=1


COPY --from=builder /app .


EXPOSE 8000


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
